from fpdf import FPDF
import pandas as pd
from datetime import datetime

class PDFReport(FPDF):
    def header(self):
        # Logo or Title
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'VIT CIVIC SENTINEL - DAILY SITUATION REPORT', 0, 1, 'C')
        self.ln(5)
        
        # Sub-header
        self.set_font('Arial', 'I', 10)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.cell(0, 10, f'Generated on: {timestamp} | Zone: Vellore', 0, 1, 'C')
        self.line(10, 30, 200, 30) # Horizontal line
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by AI System', 0, 0, 'C')

def clean_text(text):
    """
    Sanitizes text to ensure it is compatible with Latin-1 encoding (Standard PDF).
    Replaces non-supported characters with '?'.
    """
    if not isinstance(text, str):
        return str(text)
    
    # Encode to latin-1 and replace errors, then decode back to string
    return text.encode('latin-1', 'replace').decode('latin-1')

def generate_pdf(dataframe):
    pdf = PDFReport()
    pdf.add_page()
    
    # 1. EXECUTIVE SUMMARY
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'EXECUTIVE SUMMARY', 0, 1, 'L')
    
    total = len(dataframe)
    critical = len(dataframe[dataframe['priority'] == 'High'])
    avg_score = dataframe['cci'].mean()
    
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, f"Total Complaints Processed: {total}", 0, 1)
    
    # Critical Count in Red if > 0
    if critical > 0:
        pdf.set_text_color(255, 0, 0) # Red
    pdf.cell(0, 8, f"CRITICAL ALERTS (ACTION REQUIRED): {critical}", 0, 1)
    pdf.set_text_color(0, 0, 0) # Reset to black
    
    pdf.cell(0, 8, f"Average Risk Score: {avg_score:.1f} / 10", 0, 1)
    pdf.ln(10)
    
    # 2. HIGH PRIORITY ACTION LIST
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'CRITICAL INCIDENTS (HIGH PRIORITY)', 0, 1, 'L')
    
    # Filter for High Priority
    high_priority_df = dataframe[dataframe['priority'] == 'High']
    
    if not high_priority_df.empty:
        # Table Header
        pdf.set_font('Arial', 'B', 10)
        pdf.set_fill_color(200, 220, 255) # Light blue background
        pdf.cell(15, 10, 'ID', 1, 0, 'C', 1)
        pdf.cell(50, 10, 'Category', 1, 0, 'C', 1)
        pdf.cell(30, 10, 'Risk (CCI)', 1, 0, 'C', 1)
        pdf.cell(95, 10, 'Description (English)', 1, 1, 'C', 1)
        
        # Table Rows
        pdf.set_font('Arial', '', 9)
        for index, row in high_priority_df.iterrows():
            # KEY FIX: Use 'translated_text' if available, otherwise 'text'
            # This ensures we are printing English, not Tamil/Hindi
            raw_text = row.get('translated_text', row.get('text', ''))
            
            # Sanitize to remove any remaining symbols (like emojis)
            safe_text = clean_text(raw_text)
            
            # Truncate to fit table
            desc = safe_text[:60] + "..." if len(safe_text) > 60 else safe_text
            cat = clean_text(row['category'])[:25]
            
            pdf.cell(15, 10, str(row.get('id', index+1)), 1, 0, 'C')
            pdf.cell(50, 10, cat, 1, 0, 'L')
            pdf.cell(30, 10, str(row['cci']), 1, 0, 'C')
            pdf.cell(95, 10, desc, 1, 1, 'L')
    else:
        pdf.set_font('Arial', 'I', 10)
        pdf.cell(0, 10, "No High Priority incidents detected. System Status: NORMAL.", 0, 1)

    # Save to a temporary file
    file_path = "temp_report.pdf"
    pdf.output(file_path)
    return file_path
